<a href="https://colab.research.google.com/github/samratchakraborty422000/Python-basics-Assignments/blob/main/programming_assignment_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write a Python Program to Add Two Matrices?

In [3]:
import numpy as np  
#first matrix  
Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
print("Please write the elements of the matrix in a single line and separated by a space: ")    
elements = list(map(int, input().split()))   
matrix1 = np.array(elements).reshape(Rows, Columns)  
#second matrix
Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
print("Please write the elements of the matrix in a single line and separated by a space: ")    
elements = list(map(int, input().split()))   
matrix2 = np.array(elements).reshape(Rows, Columns) 
sum= matrix1+matrix2
print(f"the sum is \n {sum}")

Give the number of rows:2
Give the number of columns:2
Please write the elements of the matrix in a single line and separated by a space: 
1 2 3 4 
Give the number of rows:2
Give the number of columns:2
Please write the elements of the matrix in a single line and separated by a space: 
5 6 7 8 
the sum is 
 [[ 6  8]
 [10 12]]


2. Write a Python Program to Multiply Two Matrices?


In [6]:
import numpy as np  
#first matrix  
Rows = int(input("Give the number of rows:"))
Columns = int(input("Give the number of columns:"))  
print("Please write the elements of the matrix in a single line and separated by a space: ")    
elements = list(map(int, input().split()))   
matrix1 = np.array(elements).reshape(Rows, Columns)  
#second matrix
Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
print("Please write the elements of the matrix in a single line and separated by a space: ")    
elements = list(map(int, input().split()))   
matrix2 = np.array(elements).reshape(Rows, Columns) 
pro=np.dot(matrix1,matrix2)
print(f"the product is \n {pro}")

Give the number of rows:2
Give the number of columns:2
Please write the elements of the matrix in a single line and separated by a space: 
1 2 3 4
Give the number of rows:2
Give the number of columns:2
Please write the elements of the matrix in a single line and separated by a space: 
4 5 6 7 
the product is 
 [[16 19]
 [36 43]]


3. Write a Python Program to Transpose a Matrix?


In [7]:
import numpy as np   
Rows = int(input("Give the number of rows:"))
Columns = int(input("Give the number of columns:"))  
print("Please write the elements of the matrix in a single line and separated by a space: ")    
elements = list(map(int, input().split()))   
matrix = np.array(elements).reshape(Rows, Columns)
T=matrix.transpose()
print(T)

Give the number of rows:2
Give the number of columns:2
Please write the elements of the matrix in a single line and separated by a space: 
2 3 4 6 
[[2 4]
 [3 6]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [9]:
print("enter the words:")
l=list(map(str,input().split()))
l1=sorted(l)
print('after arranging in Alphabetical order:\n')
print(l1)

enter the words:
samrat abhi babar chana devil zomato
after arranging in Alphabetical order:

['abhi', 'babar', 'chana', 'devil', 'samrat', 'zomato']


5. Write a Python Program to Remove Punctuation From a String?

In [10]:
punctuations = '''!@#$%^&*()_+-={}:"|<>?/.,\';][*-+]'''
a=input("Enter a string: ")
l=[]
for i in a:
   if i not in punctuations:
       l.append(i)
str2=''.join(l)
print(str2)

Enter a string: "hi! I am samrat!." 
hi I am samrat 
